name: Auto Release on Master Merge

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # タグ付与・Release 作成に必要
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get next vYYYY.N version
        id: bump_version
        run: |
          year=$(date +'%Y')

          # その年の最新タグを取得
          latest_tag=$(git tag --list "v${year}.*" | sort -V | tail -n 1)
          echo "Latest tag: $latest_tag"

          if [ -z "$latest_tag" ]; then
            next_version="v${year}.1"
          else
            current_number=${latest_tag#v${year}.}
            next_number=$((current_number+1))
            next_version="v${year}.${next_number}"
          fi

          echo "next_version=$next_version" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.bump_version.outputs.next_version }}
          git push origin ${{ steps.bump_version.outputs.next_version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump_version.outputs.next_version }}
          name: Release ${{ steps.bump_version.outputs.next_version }}
          generate_release_notes: true